# -*- coding: UTF-8 -*-
#This file was originally generated by PyScripter's unitest wizard

import unittest
from micolog.utils import *

class Test_micolog_utils(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testslugify(self):
        assert slugify('this is a test')=='this-is-a-test'

    def teststrip_tags(self):
        assert strip_tags('this <a href="">xxx</a>')=='this xxx'
        assert strip_tags('this <a href="">xxx</a>',{'a':'href'})==u'this <a href="">xxx</a>'

    def testtrim_excerpt(self):
        assert trim_excerpt('aaa<br>bbb')==u'aaabbb'
        s='''<li><a href="#INSTALL">安装</a></li><li><a href="#CASEINTRO">测试用例介绍</a>'''
        assert trim_excerpt(s)==u'安装测试用例介绍'

    def testurldecode(self):
        pass

    def testurlencode(self):
        pass

    def testformat_date(self):
        pass

    def testsid(self):
        pass

if __name__ == '__main__':
    unittest.main()
